# Generated by Django 5.2 on 2025-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Expense Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Spending amount')),
                ('category', models.CharField(max_length=30, verbose_name='Type of the Expense ex: Personal, Home, etc.')),
                ('date', models.DateTimeField(help_text='The date of the expense.')),
                ('description', models.TextField(verbose_name='Description for expense.')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
