# Generated by Django 5.2 on 2025-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expense_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Home', 'Home'), ('Other', 'Other')], help_text='Type of the Expense ex: Personal, Home, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Online Payments', 'Online Payments'), ('Others', 'Others')], max_length=30, verbose_name='Payment Type'),
        ),
    ]
