# Generated by Django 5.2 on 2025-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_alter_expense_category_alter_expense_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="paid",
            field=models.CharField(
                choices=[
                    ("UPI", "UPI"),
                    ("Cash", "Cash"),
                    ("Credit Card", "Credit Card"),
                    ("Debit Card", "Debit Card"),
                    ("Gift Card", "Gift Card"),
                    ("Net Banking", "Net Banking"),
                    ("Others", "Others"),
                ],
                max_length=30,
                verbose_name="Payment Type",
            ),
        ),
    ]
